# Generated by Django 4.1.2 on 2022-11-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate', models.FloatField(default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.sponsorwallet')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_wallet', to='student.studentwallet')),
            ],
        ),
    ]
