# Generated by Django 4.1.2 on 2022-11-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_remove_sponsorwallet_spent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorwallet',
            name='spent_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
